### ISSUE TITLE
Frontend - Use triplesec in background.js

### ISSUE THREAD

**Issue by Boucher-David** [Boucher-David/Vault#61]
tripelsec is already in background.js.

Figure out how to use it to encrypt a string, using the master_key as the key.

Write two functions, one for encrypting and one for decrypting. 
Encrypting function should return a string. Take a a string as input, return it encrypted.
Decrypting should turn the decrypted string into JSON (parse) and return that object.

Will probably have to write these as async functions so you can await their result. triplesec takes ages by design.

**Comment by snlcessna** [comment]
Submitted PR (https://github.com/Boucher-David/Vault/pull/64). Complete.
